### ISSUE TITLE
Is there a chance to build upon this to get this functionality into libinput by default?

### ISSUE THREAD

**Issue by claell** [tkkcc/libinput_patch#1]
Recently I created an issue for scroll speed setting on libinput: https://gitlab.freedesktop.org/libinput/libinput/issues/185

Now I came across this repo. Is there a way to integrate this approach/a modified version of it directly into libinput?

**Comment by tkkcc** [comment]
Sorry for missing. I think it's true. It's just like using `fcitx-remote` to toggle fcitx state by a socket.
>  fcitx  will  create  socket  at /tmp/fcitx-socket-<display‐name>

libinput can init a socket too for changing delta multiplier

**Comment by claell** [comment]
Sorry for not updating this. @whot let me know that libinput is not the right place for implementation, while I think your approach is all about libinput. If you don't think this is correct, let me know. But for now I created issues to search a different approach.

**Comment by whot** [comment]
a socket that libinput can read from is just a way to go around the back of the compositor - and that's a no-go. libinput has a defined API for scroll wheel events (it provides clicks and degrees), but it doesn't have any reference to what will happen with those events. If there's an application that scrolls too little or too much, that needs to be fixed there (or in its toolkit).

This patch just goes "I want every scroll wheel click to send two clicks", just because one application doesn't work correctly. That's not the right approach, you don't change the road because one car doesn't know how to drive on it.

**Comment by tkkcc** [comment]
@whot Agree with you.

**Comment by claell** [comment]
Closing, because libinput is not the right place for an implementation.

**Comment by mikew** [comment]
I've been reading various bug reports dating back 2 or 3 years saying that libinput isn't the place for this fix.

However, using Linux in Parallels on a macbook, the scrolling is _way_ too fast. I applied this patch (using `atof` instead of `atoi`), and with this...

```
echo 0.1 > /tmp/libinput_discrete_deltay_multiplier
```

... scrolling finally feels better.

I tried using `xinput set-prop ... 'libinput Scrolling Pixel Distance' ...`, but you can see I need to scale the value down to one tenth the original. xf86-driver-libinput defaults to 15 and doesn't let you set it to a value lower than 10, so that doesn't cover my use case (not to mention the fact that changing it had no effect)
